name: deploy
on:
    push:
        branches:
            - 'build-scripts'
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: '14'
            - run: npm i
            - run: npm i -g prettier
            - run: npm run-script deploy
            - run: ls -l
